### ISSUE TITLE
Do you have any package for other type of stimulus?

### ISSUE THREAD

**Issue by YinHana0505** [nicholascarey/loomeR#45]
Hi Nicolas, 

I have managed to make the loomeR codes works on window PC now. Its great!

I would like to know if you can come up with a similar package for sweeping stimulus and circling stimulus? The sweeping stimulus would be a black dot moving across the screen diagonally at constant size and speed, while the circling stimulus would be a stimulus at constant size making a circling motion at a constant speed. I have attached some videos for your reference. 

I took these videos from youtube, but I would like to know a way to write and modify them (speed, size etc) accordingly for different experiments.

Look forward to hearing from you soon. Thank you.

https://user-images.githubusercontent.com/85520531/121782660-4de50e00-cbdd-11eb-8b19-3001be014234.mp4

https://user-images.githubusercontent.com/85520531/121782669-5d645700-cbdd-11eb-810d-8cf8ee8ba526.mp4

Yin

**Comment by nicholascarey** [comment]
That's great, I'm glad to hear it.  Can you share how you got it working or what the problem was? 

Let me know if you have any other problems with using the package. What will you be using the animations for? 

The other ones - to be honest, no. There is very little chance I will have the time to do something like this. They are even more niche or specific than looming animations are. 

I you want to look into how to make them, there are lots of options in R. I am using mostly using base R functions such as `circle()` just to draw a circle in different places and saving it as an image each time, then converting those to a movie. 

The code (which you can view from the Github) is pretty well laid out and easy to follow. You could do something similar by working out how to place it in different places like in those movies. There are also options such as the `gganimate` package. If it's for a one-off experiment, probably there are quicker and easier tools. You can even do this sort of thing in Powerpoint.

**Comment by YinHana0505** [comment]
Hi Nicholas,

It was not working at first because my Antirvirus was blocking some features of it. After I unblocked it from the antivirus software, it works well. 

I am using the animation to generate a series of different visual stimuli for mouse behavioural experiment regarding visual responsiveness. 

Thanks for your advice I am going to try out those that you suggested and see how it works.

**Comment by nicholascarey** [comment]
Ok, thanks for letting me know. 

And good luck with the experiments. Would love to hear if you use the animations and if they work ok.
